# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.provision "shell", inline: "echo Hello User"

  config.vm.define "devbox" do |devbox|
    devbox.vm.box = "ubuntu/trusty64"
    devbox.vm.provision "file", source: "app_hosting/configs/ansible_env", destination:"/home/vagrant/ansible_env"
    devbox.vm.provision "file", source: "app_hosting/configs/ansible_hosts", destination:"/home/vagrant/ansible_hosts"

    devbox.vm.network :private_network, virtualbox__intnet: "link1", ip: "10.1.1.10"
    devbox.vm.provision :shell, path: "ubuntu.sh", privileged: false
  end

  config.vm.define "rtr" do |rtr|
    rtr.vm.box = "IOS-XRv"
    rtr.vm.network :private_network, auto_config: false, virtualbox__intnet: "link1", ip: "10.1.1.20"
  end
   
end
