# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.provision "shell", inline: "echo Hello User"

  config.vm.define "devbox" do |devbox|
    devbox.vm.box = "ubuntu/trusty64"
    devbox.vm.network :private_network, virtualbox__intnet: "link1", ip: "10.1.1.10"
    # ansible_env and ansible_hosts files suited for current Ansible setup
    devbox.vm.provision "file", source: "configs/ansible_env", destination: "/home/vagrant/ansible_env"
    devbox.vm.provision "file", source: "configs/ansible_hosts", destination: "/home/vagrant/ansible_hosts"

    # cn.xml - xml descript to run container
    devbox.vm.provision "file", source: "configs/xr-lxc-app.xml", destination: "/home/vagrant/xr-lxc-app.xml"
    
    # playbook to deploy container
    devbox.vm.provision "file", source: "configs/deploy_container.yml", destination: "/home/vagrant/deploy_container.yml"
    devbox.vm.provision :shell, path: "ubuntu.sh", privileged: false
  
    devbox.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
    end
  end

  config.vm.define "rtr" do |rtr|
    rtr.vm.box = "IOS-XRv"
    rtr.vm.network :private_network, auto_config: false, virtualbox__intnet: "link1", ip: "10.1.1.20"
    rtr.vm.network "forwarded_port", id: "container-ssh", guest: 58822, host: 58822, auto_correct: true
    rtr.vm.provision "file", source: "configs/rtr_config", destination: "/home/vagrant/rtr_config"
    
    rtr.vm.provision "shell" do |s|
      s.path =  "scripts/apply_config.sh"
      s.args = ["/home/vagrant/rtr_config"]
    end
    
    rtr.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
    end
  end

end
